ACCOUNT=pi@10.0.0.232
PPATH=projects/ccam

LDFLAGS =  -g -Wall -lstdc++

%.o : %.C
	gcc -g -Wall -std=c++11 -c $< -o $@

shutdown:
	ssh ${ACCOUNT} "sudo shutdown -h now"

rccam:
	rsync -r . ${ACCOUNT}:${PPATH}
	ssh ${ACCOUNT} "cd ${PPATH} ; make eccam"

ccam: ccam.o 
	gcc $(LDFLAGS) $^ -o $@

eccam: ccam
	./ccam
